{% set version = "0.0-55.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gwidgetstcltk
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gWidgetstcltk_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gWidgetstcltk/gWidgetstcltk_{{ version }}.tar.gz
  sha256: 7389a3230af7a420fdf8fc1be08c004939285380ec4d5d3e769720558bf1b691

build:
  number: 4
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-digest
    - r-gwidgets >=0.0_51
    - tk >=8.5
    - r-tcltk2
    - r-codetools
  run:
    - r-base
    - r-digest
    - r-gwidgets >=0.0_51
    - tk >=8.5

test:
  commands:
    - xvfb-run -a bash -c "$R -e \"library('gWidgetstcltk')\""  # [linux]
    - $R -e "library('gWidgetstcltk')"  # [osx]
    - "\"%R%\" -e \"library('gWidgetstcltk')\""  # [win]

about:
  home: http://gwidgets.r-forge.r-project.org/
  license: GPL-2.0-or-later
  summary: Port of the gWidgets API to the tcltk package.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - npavlovikj

# Package: gWidgetstcltk
# Version: 0.0-55
# Title: Toolkit implementation of gWidgets for tcltk package
# Author: John Verzani
# Maintainer: John Verzani <jverzani@gmail.com>
# Depends: R (>= 2.14.0), methods, gWidgets(>= 0.0.51), tcltk(>= 2.7.0), digest
# Suggests:
# Description: Port of the gWidgets API to the tcltk package. Requires Tk 8.5 or greater.
# License: GPL (>= 2)
# URL: http://gwidgets.r-forge.r-project.org/
# LazyLoad: yes
# Packaged: 2014-07-20 19:16:46 UTC; verzani
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2014-07-20 22:19:03
