appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: eYrgrEMwmXHbVtxwyRPVu1BnVtdbtnbnM7AkmOBZxGUm9DTF6Xahrc7F6cAHu7HFARUf5RttYHQrKOaeu/Q21Ht8AYZxH25KOgIHkmdf0mDgeeZ0xmWGP/X3cPF3C3zSs07lVNy0Q5uEsPiqRsxgZ/VTY15CkV0xwPaId5+HfpItYKnBNxI64lGVmOpqo1nBeTEgJyr9Zi25rKGhpjwvQh19fb8MmTKttjKVguLxZUmBnNcWIsS9b7kEt8pnJt/wl/OaaC43Uuxyi6PThsdxJVayxJzn6u38/QHCAN89MLkaut7tzMv5lzkdvOqpOFQCME0/2XhcswTqha67qAs6d8K5cTh0+FrElefBTfaOZzxjrErlRSmAmcNQ3MNIJ5GPjJtt6nngoJquJHtDukAZCoITy3mbYmTmpIY6g52HPeyaJ2369GbQaNCqAQliRh85Am4Ju/85XzqNizyRUxjzEXR/8U4RbfJJqq85aiiI0xq4KpghITX3+D5xozfjm6Kvzg8t+Ps8uZw8en4J+DOekfaG2KdQyW6mSE6wqpLlCZC1OOhU/bJLIs+a9TK1v/JELKKiADMZGNOlH1CowUFrBw3HAAJz9cLuhor7/cYQuT5FJCZw7EIv9w/c1a0WBuuB/Ziv6wM3KhLhyQsCpQJLSJcJhmTbOZDl6c6Lsmo+mDI=
